[package]
name = "genrand"
version = "0.1.0"
authors = ["Wang Cong <ousatoru@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
